package fr.altoine.instatrain.loader;

import android.content.AsyncTaskLoader;
import android.content.Context;

/**
 * RetrofitLoader - InstaTrain
 * Created by soulierantoine on 07/08/2017
 */
public abstract class RetrofitLoader<R, S> extends AsyncTaskLoader<Response<R>> {
    private final S mService;

    private Response<R> mCachedResponse;

    public RetrofitLoader(Context context, S service) {
        super(context);
        mService = service;
    }

    /**
     * Called on a worker thread to perform the actual load.
     * Uses the call() method implemented by legacy classes.
     * @return {@link Response<R>}.
     */
    @Override
    public Response<R> loadInBackground() {
        try {
            final R data = call(mService);
            mCachedResponse = Response.ok(data);
        } catch (Exception ex) {
            mCachedResponse = Response.error(ex);
        }

        return mCachedResponse;
    }

    /**
     * Called once the loader has been generated by the loader manager (after onCreateLoader()).
     * If the loader has already performed the task, returns cached response.
     */
    @Override
    protected void onStartLoading() {
        super.onStartLoading();

        if (mCachedResponse != null) {
            deliverResult(mCachedResponse);
        }

        if (isStarted() && (takeContentChanged() || mCachedResponse == null)) {
            forceLoad();
        }
    }

    @Override
    protected void onReset() {
        super.onReset();
        mCachedResponse = null;
    }

    public abstract R call(S service);
}
